### ISSUE TITLE
Where can I get the config.json, plan.json, annotate_log.json and  ad_wizardlog.csv ?

### ISSUE THREAD

**Issue by Taoismer** [sled-group/DOROTHIE#1]
It seems that there is no these file in the pulic SDN dataset, where can I get them?

THX U!

**Comment by Mars-tin** [comment]
The game annotations and configurations are available on Dropbox: https://www.dropbox.com/sh/jqxie8hssqljmgi/AAATbEWPuo_0UU64JxOhJtk9a?dl=0.
